Trix.config.lang =
  bold: "Rasvane"
  bullets: "Täpid"
  byte:  "Bait"
  bytes: "Baiti"
  captionPlaceholder: "Trüki pealkiri siia…"
  captionPrompt: "Muuda pealkirja"
  code: "Kood"
  heading1: "Pealkiri"
  indent: "Suurenda taanet"
  italic: "Kaldkiri"
  link: "Lingi"
  numbers: "Numbrid"
  outdent: "Vähenda taanet"
  quote: "Tsiteeri"
  redo: "Tee uuesti"
  remove: "Eemalda"
  strike: "Maha tõmmatud"
  undo: "Võta tagasi"
  unlink: "Eemalda"
  urlPlaceholder: "Sisesta lingi aadress…"
  GB: "GB"
  KB: "KB"
  MB: "MB"
  PB: "PB"
  TB: "TB"
